sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t yasir6402/multi_doc_react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yasir6402/multi_doc_react npm test

after_sucess:
  - docker build -t yasir6403/multi-client ./client
  - docker build -t yasir6403/multi-nginx ./nginx
  - docker build -t yasir6403/multi-server ./server
  - docker build -t yasir6403/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yasir6403/multi-client
  - docker push yasir6403/multi-nginx
  - docker push yasir6403/multi-server
  - docker push yasir6403/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-299691650492'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  session_token: $AWS_SESSION_TOKEN