sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t yasir6402/multi_doc_react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yasir6402/multi_doc_react npm test

after_sucess:
  - docker build -t yasir6402/multi-client ./client
  - docker build -t yasir6402/multi-nginx ./nginx
  - docker build -t yasir6402/multi-server ./server
  - docker build -t yasir6402/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push yasir6402/multi-client
  - docker push yasir6402/multi-nginx
  - docker push yasir6402/multi-server
  - docker push yasir6402/multi-worker