sudo: required
language: generic

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUD_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_260d047a6042_key -iv $encrypted_260d047a6042_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multik8s-323201
  - gcloud config set compute/zone asia-southeast2-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t yasir6403/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true yasir6403/react-test npm test

after_success:
  - docker build -t yasir6403/multi-client-10-14 ./client
  - docker build -t yasir6403/multi-nginx-10-14 ./nginx
  - docker build -t yasir6403/multi-server-10-14 ./server
  - docker build -t yasir6403/multi-worker-10-14 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push yasir6403/multi-client-10-14
  - docker push yasir6403/multi-nginx-10-14
  - docker push yasir6403/multi-server-10-14
  - docker push yasir6403/multi-worker-10-14

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
